In [1]:
graph = {
    '1' : ['2'],
    '2' : ['7', '4'],
    '3' : ['4'],
    '4' : ['6'],
    '5' : ['4', '3'],
    '6' : [],
    '7' : ['5']
}
# create adjacency matrix
import numpy as np
size = len(graph.keys())
matrix = np.zeros((size,size))
# print(matrix)
for i in graph:
    # print("this is",(i))
    # print(graph[i])
    for j in graph[i]:
        # print("this is j",j)
        matrix[int(i)-1,int(j)-1] = 1
print("converting adjacency list to adjacency matrix")
print(matrix)

converting adjacency list to adjacency matrix
[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]


In [2]:
def Matrix_BFS(matrix, s):
    visited = list()
    queue   = list()      #list in python is basically queue
    visited.append(s) #means make it black
    queue.append(s)
    
    while queue:      #as long as the queue is not empty....
        u = queue.pop(0)  #pop the front guy.....basically index 0
        # print("this is row:",u-1)
        print(u, "-->", end = "")
        # print(matrix[u-1,:])
        for i in range(matrix.shape[1]):
            if matrix[u-1][i] != 0 and (i+1) not in visited:
                # print("hi")
                visited.append(i+1)              #add them to the visited
                queue.append(i+1) 
                # print("hell")
                
Matrix_BFS(matrix,1)

1 -->2 -->4 -->7 -->6 -->5 -->3 -->

In [3]:
visited = set()

def Matrix_DFS(matrix, s):
    if s not in visited:
        print(s, "--->", end="")  #our answer
        visited.add(s)
        for i in range(matrix.shape[1]):
            if matrix[s-1][i] != 0:
                # print(i)
                Matrix_DFS(matrix, i+1)
Matrix_DFS(matrix, 1)

1 --->2 --->4 --->6 --->7 --->5 --->3 --->

Case study:
1. for BFS, you can use it to see how things are connected around a specified area,like image from a satellite
2. for DFS, you can use it to find what things are on the specified path and how they are ordered, like google map